### ISSUE TITLE
Nginx permissions are not properly configured 

### ISSUE THREAD

**Issue by samiurprapon** [flywp/config#1]
# Description 
Nginx doesn't have the correct ownership.  The Nginx process inside the container needs proper permissions to read and write to these directories. In this case, the `nginxinc/nginx-unprivileged:alpine` image is set up as an unprivileged user with user ID `101`. 

```bash

fly@localhost:~/example.com$ docker inspect nginxinc/nginx-unprivileged:alpine | grep User
            "User": "",
            "User": "101",
```

I  run the Nginx container with elevated privileges for testing purposes (user: root) to see if the problem continues. If the problem disappears, it confirms that the issue is related to permissions.

I adjust the configurations accordingly and the permission issues are resolved. 

```yml
services:
  ...
  nginx:
    image: 'nginxinc/nginx-unprivileged:alpine'
    restart: always
    environment:
      - 'VIRTUAL_HOST=.example.com'
      - VIRTUAL_PORT=8080
      - 'LETSENCRYPT_HOST=example.com
    user: '101:101'  # Set the user and group ID <- my change
    volumes:
      - './app:/var/www/html'
      - './config/nginx/common:/etc/nginx/common'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './logs/nginx:/var/log/nginx'
      - './data/nginx/temp:/var/cache/nginx'
      - './data/nginx/cache:/var/run/nginx-cache'
    networks:
      - site-network
      - wordpress-sites
    depends_on:
      - PHP
     ...
```

Please have a look into this, I have also attached the logs. we are facing this issue from the very beginning. 

##  logs 

Error Message : 
```
2023/12/03 10:16:24 [crit] 43#43: *1256 rename() "/var/cache/nginx/fastcgi_temp/6/24/0000000246" to "/var/run/nginx-cache/2/92/c26a48ccb942e18274a2cbe6d142a922" 
failed (13: Permission denied) while reading upstream, client: 172.18.0.4, server: example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.2:9000", host: "example.com"
```

`example.com/data/nginx/`
```
├── cache
│   ├── 0  [error opening dir]
│   ├── 1  [error opening dir]
│   ├── 2  [error opening dir]
│   ├── 3  [error opening dir]
│   ├── 5  [error opening dir]
│   ├── 6  [error opening dir]
│   ├── 7  [error opening dir]
│   ├── a  [error opening dir]
│   ├── b  [error opening dir]
│   ├── c  [error opening dir]
│   ├── d  [error opening dir]
│   ├── e  [error opening dir]
│   └── f  [error opening dir]
└── temp
    ├── client_temp  [error opening dir]
    ├── fastcgi_temp  [error opening dir]
    ├── proxy_temp  [error opening dir]
    ├── scgi_temp  [error opening dir]
    └── uwsgi_temp  [error opening dir]
```

Permissions :
```
fly@localhost:~/example.com/data/nginx$ ll
total 16
drwxr-xr-x  4 fly             fly 4096 Dec  1 09:08 ./
drwxr-xr-x  3 fly             fly 4096 Dec  1 09:08 ../
drwxr-xr-x 15 systemd-resolve fly 4096 Dec  3 10:25 cache/
drwxr-xr-x  7 fly             fly 4096 Dec  1 09:09 temp/
```
```
fly@localhost:~/example.com/data/nginx/temp$ ll
total 28
drwxr-xr-x 7 fly             fly 4096 Dec  1 09:09 ./
drwxr-xr-x 4 fly             fly 4096 Dec  1 09:08 ../
drwx--x--x 2 systemd-resolve fly 4096 Dec  1 15:07 client_temp/
drwx--x--x 7 systemd-resolve fly 4096 Dec  3 10:07 fastcgi_temp/
drwx--x--x 2 systemd-resolve fly 4096 Dec  1 09:09 proxy_temp/
drwx--x--x 2 systemd-resolve fly 4096 Dec  1 09:09 scgi_temp/
drwx--x--x 2 systemd-resolve fly 4096 Dec  1 09:09 uwsgi_temp/
```
